name: Deploy automático do Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Executa no seu runner na cloud

    steps:
      - name: Checar repositório
        uses: actions/checkout@v3
      
      - name: Criar arquivo .env
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env

      - name: Subir containers
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
     
          
