name: Deploy automático do Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Executa no seu runner na cloud
    environment: TELEGRAM_BOT_TOKEN
    steps:
      - name: Checar repositório
        uses: actions/checkout@v3
      
      - name: Testar acesso ao Docker
        run: docker ps
      
      - name: Criar arquivo .env
        env:  
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
        run: |
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
            echo "❌ TELEGRAM_BOT_TOKEN não está definido!"
            exit 1
          else
            echo "✅ TELEGRAM_BOT_TOKEN foi carregado com sucesso!"
          fi

      - name: Subir containers
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
     
          
