name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acessar servidor e subir containers
        run: |
            docker-compose pull &&
            docker-compose up -d --build
          "
